//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7b.PhoneDictService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int Phone_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Phone_Number {
            get {
                return this.Phone_NumberField;
            }
            set {
                if ((this.Phone_NumberField.Equals(value) != true)) {
                    this.Phone_NumberField = value;
                    this.RaisePropertyChanged("Phone_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneDictService.PhoneDictServiceSoap")]
    public interface PhoneDictServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Lab7b.PhoneDictService.HelloWorldResponse HelloWorld(Lab7b.PhoneDictService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.HelloWorldResponse> HelloWorldAsync(Lab7b.PhoneDictService.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDictResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        Lab7b.PhoneDictService.GetDictResponse GetDict(Lab7b.PhoneDictService.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.GetDictResponse> GetDictAsync(Lab7b.PhoneDictService.GetDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        Lab7b.PhoneDictService.AddDictResponse AddDict(Lab7b.PhoneDictService.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.AddDictResponse> AddDictAsync(Lab7b.PhoneDictService.AddDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        Lab7b.PhoneDictService.UpdDictResponse UpdDict(Lab7b.PhoneDictService.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.UpdDictResponse> UpdDictAsync(Lab7b.PhoneDictService.UpdDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        Lab7b.PhoneDictService.DelDictResponse DelDict(Lab7b.PhoneDictService.DelDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.DelDictResponse> DelDictAsync(Lab7b.PhoneDictService.DelDictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab7b.PhoneDictService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab7b.PhoneDictService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(Lab7b.PhoneDictService.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(Lab7b.PhoneDictService.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b.PhoneDictService.Phone[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(Lab7b.PhoneDictService.Phone[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(Lab7b.PhoneDictService.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b.PhoneDictService.Phone phone;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(Lab7b.PhoneDictService.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(Lab7b.PhoneDictService.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDictResponseBody {
        
        public AddDictResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(Lab7b.PhoneDictService.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b.PhoneDictService.Phone phone;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(Lab7b.PhoneDictService.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(Lab7b.PhoneDictService.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdDictResponseBody {
        
        public UpdDictResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.DelDictRequestBody Body;
        
        public DelDictRequest() {
        }
        
        public DelDictRequest(Lab7b.PhoneDictService.DelDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b.PhoneDictService.Phone phone;
        
        public DelDictRequestBody() {
        }
        
        public DelDictRequestBody(Lab7b.PhoneDictService.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.PhoneDictService.DelDictResponseBody Body;
        
        public DelDictResponse() {
        }
        
        public DelDictResponse(Lab7b.PhoneDictService.DelDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DelDictResult;
        
        public DelDictResponseBody() {
        }
        
        public DelDictResponseBody(bool DelDictResult) {
            this.DelDictResult = DelDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhoneDictServiceSoapChannel : Lab7b.PhoneDictService.PhoneDictServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneDictServiceSoapClient : System.ServiceModel.ClientBase<Lab7b.PhoneDictService.PhoneDictServiceSoap>, Lab7b.PhoneDictService.PhoneDictServiceSoap {
        
        public PhoneDictServiceSoapClient() {
        }
        
        public PhoneDictServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneDictServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneDictServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneDictServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.PhoneDictService.HelloWorldResponse Lab7b.PhoneDictService.PhoneDictServiceSoap.HelloWorld(Lab7b.PhoneDictService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab7b.PhoneDictService.HelloWorldRequest inValue = new Lab7b.PhoneDictService.HelloWorldRequest();
            inValue.Body = new Lab7b.PhoneDictService.HelloWorldRequestBody();
            Lab7b.PhoneDictService.HelloWorldResponse retVal = ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.HelloWorldResponse> Lab7b.PhoneDictService.PhoneDictServiceSoap.HelloWorldAsync(Lab7b.PhoneDictService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.PhoneDictService.HelloWorldResponse> HelloWorldAsync() {
            Lab7b.PhoneDictService.HelloWorldRequest inValue = new Lab7b.PhoneDictService.HelloWorldRequest();
            inValue.Body = new Lab7b.PhoneDictService.HelloWorldRequestBody();
            return ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.PhoneDictService.GetDictResponse Lab7b.PhoneDictService.PhoneDictServiceSoap.GetDict(Lab7b.PhoneDictService.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public Lab7b.PhoneDictService.Phone[] GetDict() {
            Lab7b.PhoneDictService.GetDictRequest inValue = new Lab7b.PhoneDictService.GetDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.GetDictRequestBody();
            Lab7b.PhoneDictService.GetDictResponse retVal = ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.GetDictResponse> Lab7b.PhoneDictService.PhoneDictServiceSoap.GetDictAsync(Lab7b.PhoneDictService.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.PhoneDictService.GetDictResponse> GetDictAsync() {
            Lab7b.PhoneDictService.GetDictRequest inValue = new Lab7b.PhoneDictService.GetDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.GetDictRequestBody();
            return ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.PhoneDictService.AddDictResponse Lab7b.PhoneDictService.PhoneDictServiceSoap.AddDict(Lab7b.PhoneDictService.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public void AddDict(Lab7b.PhoneDictService.Phone phone) {
            Lab7b.PhoneDictService.AddDictRequest inValue = new Lab7b.PhoneDictService.AddDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.AddDictRequestBody();
            inValue.Body.phone = phone;
            Lab7b.PhoneDictService.AddDictResponse retVal = ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).AddDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.AddDictResponse> Lab7b.PhoneDictService.PhoneDictServiceSoap.AddDictAsync(Lab7b.PhoneDictService.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.PhoneDictService.AddDictResponse> AddDictAsync(Lab7b.PhoneDictService.Phone phone) {
            Lab7b.PhoneDictService.AddDictRequest inValue = new Lab7b.PhoneDictService.AddDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.AddDictRequestBody();
            inValue.Body.phone = phone;
            return ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.PhoneDictService.UpdDictResponse Lab7b.PhoneDictService.PhoneDictServiceSoap.UpdDict(Lab7b.PhoneDictService.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public void UpdDict(Lab7b.PhoneDictService.Phone phone) {
            Lab7b.PhoneDictService.UpdDictRequest inValue = new Lab7b.PhoneDictService.UpdDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.UpdDictRequestBody();
            inValue.Body.phone = phone;
            Lab7b.PhoneDictService.UpdDictResponse retVal = ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).UpdDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.UpdDictResponse> Lab7b.PhoneDictService.PhoneDictServiceSoap.UpdDictAsync(Lab7b.PhoneDictService.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.PhoneDictService.UpdDictResponse> UpdDictAsync(Lab7b.PhoneDictService.Phone phone) {
            Lab7b.PhoneDictService.UpdDictRequest inValue = new Lab7b.PhoneDictService.UpdDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.UpdDictRequestBody();
            inValue.Body.phone = phone;
            return ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.PhoneDictService.DelDictResponse Lab7b.PhoneDictService.PhoneDictServiceSoap.DelDict(Lab7b.PhoneDictService.DelDictRequest request) {
            return base.Channel.DelDict(request);
        }
        
        public bool DelDict(Lab7b.PhoneDictService.Phone phone) {
            Lab7b.PhoneDictService.DelDictRequest inValue = new Lab7b.PhoneDictService.DelDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.DelDictRequestBody();
            inValue.Body.phone = phone;
            Lab7b.PhoneDictService.DelDictResponse retVal = ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).DelDict(inValue);
            return retVal.Body.DelDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.PhoneDictService.DelDictResponse> Lab7b.PhoneDictService.PhoneDictServiceSoap.DelDictAsync(Lab7b.PhoneDictService.DelDictRequest request) {
            return base.Channel.DelDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.PhoneDictService.DelDictResponse> DelDictAsync(Lab7b.PhoneDictService.Phone phone) {
            Lab7b.PhoneDictService.DelDictRequest inValue = new Lab7b.PhoneDictService.DelDictRequest();
            inValue.Body = new Lab7b.PhoneDictService.DelDictRequestBody();
            inValue.Body.phone = phone;
            return ((Lab7b.PhoneDictService.PhoneDictServiceSoap)(this)).DelDictAsync(inValue);
        }
    }
}
